
import { ContentLayout } from '@/components/layout/content-layout';

export default function TermsOfServicePage() {
  return (
    <ContentLayout title="Terms of Service">
      <div className="prose prose-invert max-w-none text-muted-foreground">
        <p>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <h2>1. Agreement to Terms</h2>
        <p>
          By using our Service, you agree to be bound by these Terms. If you
          disagree with any part of the terms, then you do not have permission
          to access the Service.
        </p>

        <h2>2. Use of Service</h2>
        <p>
          EffectSpark grants you a non-transferable, non-exclusive, revocable,
          limited license to use and access the Service solely for your own
          personal, noncommercial use. The ideas generated by the AI are for
          inspiration and should be adapted and modified. You are responsible
          for the content you create and for ensuring it complies with TikTok's
          terms and community guidelines.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          When you create an account with us, you guarantee that you are above
          the age of 13, and that the information you provide us is accurate,
          complete, and current at all times. You are responsible for
          safeguarding the password that you use to access the Service and for
          any activities or actions under your password.
        </p>
        
        <h2>4. Intellectual Property</h2>
        <p>
          The Service and its original content (excluding content provided by
          users), features and functionality are and will remain the exclusive
          property of EffectSpark and its licensors.
        </p>

        <h2>5. Termination</h2>
        <p>
          We may terminate or suspend your account and bar access to the Service
          immediately, without prior notice or liability, under our sole
          discretion, for any reason whatsoever and without limitation,
          including but not limited to a breach of the Terms.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          In no event shall EffectSpark, nor its directors, employees, partners,
          agents, suppliers, or affiliates, be liable for any indirect,
          incidental, special, consequential or punitive damages, including
          without limitation, loss of profits, data, use, goodwill, or other
          intangible losses, resulting from your access to or use of or
          inability to access or use the Service.
        </p>

        <h2>7. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace
          these Terms at any time. We will provide at least 30 days' notice
          prior to any new terms taking effect.
        </p>

        <h2>Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at
          legal@effectspark.com.
        </p>
      </div>
    </ContentLayout>
  );
}
